version: "3"

services:
  mysql:
    container_name: reflexa-mysql
    image: mysql
    env_file:
      - .env
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
